<div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php // <-- Add this !!
                            echo $this->navigation('navigation')
                             ->menu()
                             ->setMinDepth(0)
                             ->setMaxDepth(0)
                             ->setUlClass('nav navbar-nav');               
                        ?>
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
         <div><!--/.nav-collapse -->

<div class="container">
            <?php echo $this->content; ?>
</div>