<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Register: Cape Kidney Association ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . 'css/style1.css')
                ->prependStylesheet($this->basePath() . 'css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

        
        
        
     <!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Cape Kidney Association">
	<meta name="author" content="Group 3">	
	<title>Gallery: Cape Kidney Association</title>
	<link rel="favicon" href="images/favicon.png">	
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="css/bootstrap-theme.css" media="screen" >
    <link rel="stylesheet" type="text/css" href="css/isotope.css" media="screen" />
    <link rel="stylesheet" href="js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="css/style.css">
	
        
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="index.html"><img style="position:absolute; top:15px;" src="images/logo.png" alt="logo"></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<ul class="nav navbar-nav pull-right">
			    
                            <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a></li>
                            <li><a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a></li>
                             <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
                             <li><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
                                   <li><a href="https://capekidneyass.wordpress.com">Blog</a></li>
                              <li><a href="<?php echo $this->url('donations') ?>"><?php echo $this->translate('Donations') ?></a></li>
                             
					<li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
					<li class="active"><a class="btn" href="register">SIGN IN / SIGN UP</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div> 
            </header>
    <div class='c'></div>
     <div class="slider">
            </div>
         <div class="home-wrapper">
</br></br></br></br></br></br>
 <h1>Registration</h1>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('register/default', array('controller' => 'registration', 'action' => 'index')));

$form->prepare();

$form->get('first_name')->setAttributes(array(
     'class'=>'form-control',
    'placeholder'=>'first name'
     ));

$form->get('usr_name')->setAttributes(array(
     'class'=>'form-control',
    'placeholder'=>'user name'
     ));

    $form->get('usr_email')->setAttributes(array(
    'class'=>'form-control',
        'placeholder'=>'user email'
     ));
     
      $form->get('usr_password')->setAttributes(array(
     'class'=>'form-control',
          'placeholder'=>'password'
     ));
    
     $form->get('usr_password_confirm')->setAttributes(array(
     'class'=>'form-control',
     'placeholder'=>'confirm password'
     ));
     
//      $form->get('captcha')->setAttributes(array(
//     'class'=>'form-control',
//     ));
     $form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
 ?>

<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->form()->openTag($form);
        ?>
        
         <div class="form-group" >
             <?php echo $this->formLabel($form->get('first_name')); ?>
             <?php echo $this->formElement($form->get('first_name')); ?>
             <?php echo $this->formElementErrors($form->get('first_name')); ?>
        </div>
        
        <div class="form-group" >
             <?php echo $this->formLabel($form->get('usr_name')); ?>
             <?php echo $this->formElement($form->get('usr_name')); ?>
             <?php echo $this->formElementErrors($form->get('usr_name')); ?>
        </div>
        
        <div class="form-group">
             <?php echo $this->formLabel($form->get('usr_email')); ?>
             <?php echo $this->formElement($form->get('usr_email')); ?>
             <?php echo $this->formElementErrors($form->get('usr_email')); ?>
         </div>
        
         <div class="form-group">
             <?php echo $this->formLabel($form->get('usr_password')); ?>
             <?php echo $this->formElement($form->get('usr_password')); ?>
             <?php echo $this->formElementErrors($form->get('usr_password')); ?>
         </div>
        
         <div class="form-group">
             <?php echo $this->formLabel($form->get('usr_password_confirm')); ?>
             <?php echo $this->formElement($form->get('usr_password_confirm')); ?>
             <?php echo $this->formElementErrors($form->get('usr_password_confirm')); ?>
         </div>
        
        <?php echo $this->formElement($form->get('csrf')); ?>
        
         <div class="form-group">
            <?php //echo $this->formRow($form->get('captcha')) ; echo "<br/>"; ?>
         </div>
        
        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); echo "<br/>"?>
        </div>
             <?php echo $this->form()->closeTag(); ?> 
        </div>
</div>
            
 </div>

    <footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					<div class="col-md-5 panel">
						<h3 class="panel-title">Latest News</h3>
						<div class="panel-body">
							<p>The Cape Kidney Association this year was invited to exhibit at the World Congress of Nephrology that was held for the first time in South Africa at the CTICC with approximately 3000 medical specialists attending the congress.
            At the congress our Executive Fund Manager, Molly Fabe was appointed as the ambassador for South Africa. We also had our first international booklet about the company published by our interns Sisonke and Pumela and it was distributed to every delegate during the congress.</p> 
						</div>
					</div>

					<div class="col-md-4 panel contact"> 
						<h3 class="panel-title">Contact Info</h4>
						<div class="panel-body">
						<p>The Cape Kidney Association is managed by Molly Fabe, Executive Manager, and assisted by Vanessa Hallet, Office Administrator.</p>
						<ul>
						  <li><i class="fa fa-phone"></i>021 761 1326</li>
						  <li><a href="mailto:capekidney@xsinet.co.za"><i class="fa fa-envelope-o"></i> capekidney@xsinet.co.za</a></li>
						  <li><i class="fa fa-flag"></i>17 Torrens Road Golf Link Estate Wynberg 7800</li>
						</ul>
						</div>
					</div>

					<div class="col-md-3 panel">
						<h3 class="panel-title">Follow Us</h3>
						<div class="panel-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								
								
								<a href="https://www.facebook.com/CapeKidneyAssociation?fref=ts"><i class="fa fa-facebook fa-2"></i></a>
								
							</p>	
						</div>
					</div>
			
				</div> <!-- /row of panels -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="simplenav">
								<a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a> | <a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a> | <a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a> | <a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a> | <a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a> | <a href="<?php echo $this->url('news') ?>"><?php echo $this->translate('Newsletter') ?> </a> </p> 
							</p>
						</div>
					</div>

					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="text-right">
								<a href="index2.html"><img src="img/images/f.png" alt="" width="100" height="25" /></a>                                                                                                                                                                                                                                                                                                                                                                                                                                  
				<a href="index2.html"><img src="img/images/g.png" alt="" width="100" height="25" /></a>                         
				<a href="index2.html"><img src="img/images/l.jpg" alt="" width="130" height="25" /></a>                        
				<a href="index2.html"><img src="img/images/m.png" alt="" width="100" height="25" /></a>               
 
							</p>
						</div>
					</div>

				</div> <!-- /row of panels -->
			</div>
		</div>

	</footer>
        
        
        
        <!-- JavaScript libs are placed at the end of the document so the pages load faster, is what I heard. -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="js/headroom.min.js"></script>
	<script src="js/jQuery.headroom.min.js"></script>
	<script src="js/custom.js"></script>
        
    </body>
</html>
