<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Cape Kidney Association ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . 'css/style.css')
                ->prependStylesheet($this->basePath() . 'css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Cape Kidney Association">
	<meta name="author" content="Group 3">	
	<title>About us: Cape Kidney Association</title>
	<link rel="favicon" href="images/favicon.png">	
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="css/style.css">

        
</head>

<body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="index.html"><img style="position:absolute; top:15px;" src="images/logo.png" alt="logo"></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                                        <li class="active"><a href="#">About Us</a></li>
                            <li><a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a></li>
                             <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
                             
                              <li><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
                                   <li><a href="https://capekidneyass.wordpress.com">Blog</a></li>
                              <li><a href="<?php echo $this->url('donations') ?>"><?php echo $this->translate('Donations') ?></a></li>
                              
                                
                                        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
					<li><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
					
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div> 
	<!-- /.navbar -->

	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-8 maincontent">
				<header class="page-header">
					<h1 class="page-title">About us</h1>
				</header>
				<h3>Our Company</h3>
				<p><img src="images/about.png" alt="" class="img-rounded pull-right" width="300" > The Cape Kidney Association (CKA) is a grassroots non-profit organization which was established in 1978 and is involved in raising awareness about maintaining kidney health and preventing kidney failure. In addition the CKA is involved in fundraising efforts to assist indigent patients with chronic kidney failure on dialysis. The CKA provides the indigent patients with nutritious food parcels, study bursaries and assist their entrepreneurship projects so that they can sustain themselves financially and regain their self-esteem.</p>
				<p></p>
				
                                <h3>Company Goals</h3>
				<p>We supply food parcels to indigent patients on a monthly basis to Provincial Hospital, and we have now extended the distribution to renal units in surrounding areas of the Western Cape. We provide families with financial support to start up small businesses. Due to our Indigent Kidney patients having to be on dialysis three (3) times per week for four (4) hours, they are not always able to maintain their jobs, therefore we assist them to become self-employed. We provide bursaries for patients who wish to continue their studies.  Patients, due to lack of funds within the families, are assisted in order to find sustainable jobs.
                                    We provide funds to the Social Workers at the Provincial Hospitals. These funds are used to assist the patients with transport costs to get to the hospitals for their dialysis and to collect medication which they require daily. We embark on public education by means of exhibitions in shopping centers as well as distribution of pamphlets and brochures.  We also present talks on ‘Caring for your Kidneys” at Corporate Companies, social groups and schools on request, as well as arranging ‘Wellness Days’.</p>
				
                                <h3>Mission Statement</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente. voluptate minus illo tenetur sint ab in culpa cumque impedit quibusdam. Saepe, molestias quia voluptatem natus velit fugiat omnis rem eos sapiente quasi quaerat aspernatur quisquam deleniti accusantium laboriosam odio id?</p>
				
                                <h3>Important News</h3>
				<p>Kidney disease is a silent enemy that can attack anyone.  No age is immune from this sickness, and can drastically affect one’s life-style. Consult your Doctor if any of these symptoms occur.  Kidney disease leads to kidney failure which is life threatening.  Special therapy is required e.g. dialysis of which there are two types, namely Haemodialysis and Peritoneal dialysis. Kidney transplantation however is still the best form of therapy.</p>
				<p>Chronic Kidney Disease is another common, life-threatening illness that often goes undetected until very advanced when it could be diagnosed early through simple tests. Today’s epidemics of diabetes and obesity could contribute to even higher rates of Chronic Kidney Disease in the future.  Undiagnosed and untreated chronic kidney disease can lead to serious health problems including kidney failure.  Diagnosed early, it can be managed, and kidney damage can be slowed or stopped, that is why testing for people at risk is so important.  If you have diabetes, high blood pressure or a family history of kidney disease, you’re at risk and should request your doctor about the simple tests for kidney function.</p>
				
			</article>
			<!-- /Article -->
			
			<!-- Sidebar -->
			<aside class="col-sm-4 sidebar sidebar-right">

				
				
				     
        <div class="wrap one-line-heading"><h2 class="line"></h2><div class="line-after" style="width: 198px;"></div></div>
        

			</aside>
			<!-- /Sidebar -->

		</div>
	
	 
	</div>	<!-- /container -->
	
	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					<div class="col-md-5 panel">
						<h3 class="panel-title">Latest News</h3>
						<div class="panel-body">
							<p>The Cape Kidney Association this year was invited to exhibit at the World Congress of Nephrology that was held for the first time in South Africa at the CTICC with approximately 3000 medical specialists attending the congress.
            At the congress our Executive Fund Manager, Molly Fabe was appointed as the ambassador for South Africa. We also had our first international booklet about the company published by our interns Sisonke and Pumela and it was distributed to every delegate during the congress.</p> 
						</div>
					</div>

				<div class="col-md-4 panel contact"> 
						<h3 class="panel-title">Contact Info</h4>
						<div class="panel-body">
						<p>The Cape Kidney Association is managed by Molly Fabe, Executive Manager, and assisted by Vanessa Hallet, Office Administrator.</p>
						<ul>
						  <li><i class="fa fa-phone"></i>021 761 1326</li>
						  <li><a href="mailto:capekidney@xsinet.co.za"><i class="fa fa-envelope-o"></i> capekidney@xsinet.co.za</a></li>
						  <li><i class="fa fa-flag"></i>17 Torrens Road Golf Link Estate Wynberg 7800</li>
						</ul> 
						</div>
					</div>

					<div class="col-md-3 panel">
						<h3 class="panel-title">Follow Us</h3>
						<div class="panel-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								
								
								<a href="https://www.facebook.com/CapeKidneyAssociation?fref=ts"><i class="fa fa-facebook fa-2"></i></a>
								
							</p>	
						</div>
					</div>
			
				</div> <!-- /row of panels -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="simplenav">
								<a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a> | <a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a> | <a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a> | <a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a> | <a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a> | <a href="<?php echo $this->url('news') ?>"><?php echo $this->translate('Newsletter') ?> </a> </p>
							</p>
						</div>
					</div>

					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="text-right">
								<a href="index2.html"><img src="img/images/f.png" alt="" width="100" height="25" /></a>                                                                                                                                                                                                                                                                                                                                                                                                                                  
				<a href="index2.html"><img src="img/images/g.png" alt="" width="100" height="25" /></a>                         
				<a href="index2.html"><img src="img/images/l.jpg" alt="" width="130" height="25" /></a>                        
				<a href="index2.html"><img src="img/images/m.png" alt="" width="100" height="25" /></a>               
 
							</p>
						</div>
					</div>

				</div> <!-- /row of panels -->
			</div>
		</div>

	</footer>	
		




	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="js/headroom.min.js"></script>
	<script src="js/jQuery.headroom.min.js"></script>
	<script src="js/custom.js"></script>
</body>
</html>
        
        
        
        
        
        
        
        
        
        
        
        
  
