<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('THE ' . $this->translate('HOMESTEAD'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style1.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <body>
       <div id="wrapper">
		<div id="header">
                    <a href="<?php echo $this->url('home') ?>" class="logo"><img src="img/images/logo.png" width="250" height="109" /></a>																																																																																																																							
			<div id="menu">
		            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('') ?></a></li>
                            <li><a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a></li>
                             <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
                             <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a></li>
                              <li><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
                              <li><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('blog') ?></a></li>
                              <li><a href="<?php echo $this->url('donations') ?>"><?php echo $this->translate('Donations') ?></a></li>
                              <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
			</div>
                        <br>
			
		</div>
		<div id="content">	
                    
                    
			
		</div>
		<div id="footer">
			<div id="bottom_navigation">
				<a href="index2.html"><img src="img/images/f.png" alt="" width="100" height="25" /></a>                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="inner_copy"><a href="http://www.webbuildersguide.com/website-builder-categories/best-website-builders-for-nonprofit-organizations/">Source: Best Website Builders for Nonprofit Organizations</a></div>
				<a href="index2.html"><img src="img/images/g.png" alt="" width="100" height="25" /></a>                         
				<a href="index2.html"><img src="img/images/l.jpg" alt="" width="130" height="25" /></a>                        
				<a href="index2.html"><img src="img/images/m.png" alt="" width="100" height="25" /></a>               

			</div>
			<div id="copy">
				Copyright &copy;. All rights reserved. 																																																																																																																																														 
			</div>
		</div>
	</div>
<map name="Map">
	<area shape="rect" coords="145,270,336,295" href="#">
</map>
</body>
</html>
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

