<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Cape Kidney Association ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style1.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

<meta charset="utf-8">
<meta name="viewport"    content="width=device-width, initial-scale=1.0">
<meta name="description" content="Cape Kidney Association">
<meta name="author" content="Group 3">
<title>Home: Cape Kidney Association</title>
<link rel="favicon" href="images/favicon.png">
<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<!-- Custom styles for our website -->
<link rel="stylesheet" href="css/bootstrap-theme.css" media="screen" >
<link rel="stylesheet" type="text/css" href="css/da-slider.css" />
<link rel="stylesheet" href="css/style.css">




</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
  <div class="container">
    <div class="navbar-header"> 
      <!-- Button for smallest screens -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <a class="navbar-brand" href="index.html"><img style="position:absolute; top:15px;" src="images/logo.png" alt="logo"></a> </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li class="active" ><a href="#">Home</a></li> 
     <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a></li> 
        <li><a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a></li>
        <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
        <li><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
          <li><a href="https://capekidneyass.wordpress.com">Blog</a></li>
          <li><a href="<?php echo $this->url('donations') ?>"><?php echo $this->translate('Donations') ?></a></li>
         
        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
        <li><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
      </ul>
    </div>
    <!--/.nav-collapse --> 
  </div>
</div>
<!-- /.navbar --> 

<!-- Header -->

<!-- /Header --> 

<!-- Intro -->
<div class="container text-center sectionBox herotxt">
  </br></br></br><h2 >Welcome to the Cape Kidney Association!</h2>
  <p class="text-muted"> With this website, we intend to make it a means of communication to keep in touch with news and activities which relate to the association.</p>
</div>
<!-- /Intro--> 

<!-- Highlights - jumbotron -->
<div class="jumbotron sectionBox">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption">
          <h4><i class="fa fa-users fa-2x circle"></i>Four Golden Rules to reduce risk are:</h4>
        </div>
        <div class="h-body text-center">
            
          
	<li span style ="Color: white;">Keep fit and active</li>
	<li span style ="Color: white;">Monitor your blood and sugar level.</li>
	<li span style ="Color: white;">Eat healthy, drink water and keep weight healthy.</li>
        <li span style ="Color: white;">Don't smoke or take pills regularly.</li>
        <li span style ="Color: white;">Check kidney function if you have one or more of these.</li>
	
            
        </div>
      </div>
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption">
          <h4><i class="fa fa-bar-chart-o fa-2x circle"></i>Upcoming Events</h4>
        </div>
        <div class="h-body text-center"> 
            
            <li span style ="Color: white;"> 25 September: Spring Dance at Claremont Civic Center</li>
            <li span style ="Color: white;"> 28 November: Race Day at Kenilworth Race Course</li>
            <li span style ="Color: white;"> December: CHarity Christmas Cards at Claremont Cavendish</li>
          
          
        </div>
      </div>
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption">
          <h4><i class="fa fa-gears fa-2x circle"></i>What do normal Kidneys do?</h4>
        </div>
        <div class="h-body text-center">
            
            <li span style ="Color: white;"> Make Urine.</li> 
            <li span style ="Color: white;">Remove waste and fluid from blood.</li>
              <li span style ="Color: white;"> Help control your blood pressure.</li>
                <li span style ="Color: white;"> Helps keep bones healthy.</li>
                  <li span style ="Color: white;"> Helps you make red blood cells.</li>
            
            
        </div>
      </div>
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption">
          <h4><i class="fa fa-file-word-o fa-2x circle"></i>How healthy are your Kidneys</h4>
        </div>
        <div class="h-body text-center">
           <li span style ="Color: white;">Do I have high blood pressure?</li>
             <li span style ="Color: white;">Do I suffer from diabetes?</li>
               <li span style ="Color: white;"> Do I have a family history of kidney disease?</li>
                 <li span style ="Color: white;">Am I overweight?</li>
                   <li span style ="Color: white;">Do I smoke?</li>
                     <li span style ="Color: white;">Am I over 50 Years old?</li>
        </div>
      </div>
    </div>
    <!-- /row  --> 
    
  </div>
</div>
<!-- /Highlights -->
<section class="sectionBox">
  <div class="container">
    <div class="row">
      <div class='col-md-offset-2 col-md-8 text-center'>
        <h2>Testimonial</h2>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-offset-2 col-md-8'>
        <div class="carousel slide" data-ride="carousel" id="quote-carousel"> 
          <!-- Bottom Carousel Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#quote-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#quote-carousel" data-slide-to="1"></li>
            <li data-target="#quote-carousel" data-slide-to="2"></li>
          </ol>
          
          <!-- Carousel Slides / Quotes -->
          <div class="carousel-inner"> 
            
            <!-- Quote 1 -->
            <div class="item active">
              <blockquote>
                <div class="row">
                  <div class="col-sm-3 text-center"> <img class="img-circle" src="images/person_1.png" style="width: 100px;height:100px;"> </div>
                  <div class="col-sm-9">
                    <p>Working with the foundation has given me appreciation for life and respect for my kidneys.</p>
                    <small>Molly Fabe</small> </div>
                </div>
              </blockquote>
            </div>
            <!-- Quote 2 -->
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-3 text-center"> <img class="img-circle" src="images/" style="width: 100px;height:100px;"> </div>
                  <div class="col-sm-9">
                    <p>Kidneys are just as important as the heart yet it is taken for granted.</p>
                    <small>Dr</small> </div>
                </div>
              </blockquote>
            </div>
            <!-- Quote 3 -->
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-3 text-center"> <img class="img-circle" src="images/person_3.png" style="width: 100px;height:100px;"> </div>
                  <div class="col-sm-9">
                    <p>Love yourself, love your health and love your kidneys.</p>
                    <small>Vanessa Hallet</small> </div>
                </div>
              </blockquote>
            </div>
          </div>
          
          <!-- Carousel Buttons Next/Prev --> 
          <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a> <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a> </div>
      </div>
    </div>
  </div>
</section>
<section class="sectionBox">
<div class="container">
  <div class="heading"> 
    <!-- Heading -->
    <h2>About the Company</h2>
    <br/>
  </div>
  <div class="row">
    <div class="col-md-4"> <img src="images/building.png" alt="" class="img-responsive"> </div>
    <div class="col-md-8">
      <p>The Cape Kidney Association is a grassroots Non-Profit Organization that raises funds for indigent kidney patients at the various Provincial Hospitals in and around the greater Western Cape Area.The main focus of the Cape Kidney Association is to assist Indigent kidney patients.
            We supply food parcels to indigent patients on a monthly basis to Provincial Hospital, and we have now extended the distribution to renal units in surrounding areas of the Western Cape.</p>
      
    </div>
  </div>
</div>
</section>
<!-- container -->

<footer id="footer" class="top-space">
  <div class="footer1">
    <div class="container">
      <div class="row">
        <div class="col-md-5 panel">
          <h3 class="panel-title">Latest News</h3>
          <div class="panel-body">
            <p>The Cape Kidney Association this year was invited to exhibit at the World Congress of Nephrology that was held for the first time in South Africa at the CTICC with approximately 3000 medical specialists attending the congress.
            At the congress our Executive Fund Manager, Molly Fabe was appointed as the ambassador for South Africa. We also had our first international booklet about the company published by our interns Sisonke and Pumela and it was distributed to every delegate during the congress.</p>
          </div>
        </div>
        <div class="col-md-4 panel contact"> 
						<h3 class="panel-title">Contact Info</h4>
						<div class="panel-body">
						<p>The Cape Kidney Association is managed by Molly Fabe, Executive Manager, and assisted by Vanessa Hallet, Office Administrator.</p>
						<ul>
						  <li><i class="fa fa-phone"></i>021 761 1326</li>
						  <li><a href="mailto:capekidney@xsinet.co.za"><i class="fa fa-envelope-o"></i> capekidney@xsinet.co.za</a></li>
						  <li><i class="fa fa-flag"></i>17 Torrens Road Golf Link Estate Wynberg 7800</li>
						</ul> 
						</div>
					</div>
        <div class="col-md-3 panel">
						<h3 class="panel-title">Follow Us</h3>
						<div class="panel-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								
								
								<a href="https://www.facebook.com/CapeKidneyAssociation?fref=ts"><i class="fa fa-facebook fa-2"></i></a>
								
							</p>	
						</div>
					</div>
      </div>
      <!-- /row of panels --> 
    </div>
  </div>
  <div class="footer2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="simplenav"> <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a> | <a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a> | <a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a> | <a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a> | <a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?> </a> | <a href="<?php echo $this->url('news') ?>"><?php echo $this->translate('Newsletter') ?> </a> </p>
          </div>
        </div>
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="text-right"> 
                    <div class="inner_copy"> <p>
                
                            <a href="index2.html"><img src="img/images/f.png" alt="" width="100" height="25" /></a>                                                                                                                                                                                                                                                                                                                                                                                                                                  
				<a href="index2.html"><img src="img/images/g.png" alt="" width="100" height="25" /></a>                         
				<a href="index2.html"><img src="img/images/l.jpg" alt="" width="130" height="25" /></a>                        
				<a href="index2.html"><img src="img/images/m.png" alt="" width="100" height="25" /></a>   
                            
                            
                </p>
          </div>
        </div>
      </div>
      <!-- /row of panels --> 
    </div>
  </div>
</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster --> 
<script src="js/modernizr-latest.js"></script> 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> 
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script> 
<script src="js/jquery.cslider.js"></script> 
<script src="js/headroom.min.js"></script> 
<script src="js/jQuery.headroom.min.js"></script> 
<script src="js/custom.js"></script>
</body>
</html>
