<?php echo $this->doctype(); ?>
  


<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Cape Kidney Association ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style1.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->
        <meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Cape Kidney Association">
	<meta name="author" content="Group 3">
	<title>Kidney Disease: Cape Kidney Association</title>
	<link rel="favicon" href="images/favicon.png">
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="css/style.css">
	
</head>

<body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="index.phtml"><img style="position:absolute; top:15px;" src="images/logo.png" alt="logo"></a>
			</div>
			<div class="navbar-collapse collapse">
			
				
					
                                        
                                        <ul class="nav navbar-nav pull-right">
					<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                                        <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a></li>
                                        <li class="active"><a href="#">Kidney Disease</a></li>
                              <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
                              <li><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
                                   <li><a href="https://capekidneyass.wordpress.com">Blog</a></li>
                              <li><a href="<?php echo $this->url('donations') ?>"><?php echo $this->translate('Donations') ?></a></li>
                              
        
                                        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
					<li><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
					
				</ul>
					
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div> 
	<!-- /.navbar -->

	<header id="head" class="secondary"></header>
    <div class="container serviceslist">
      <div class="row">
      <div class="col-md-12">
        <header class="page-header">
					<h1 class="page-title">Kidney Disease</h1>
				</header> 
                </div>
         </div>       
      <div class="row">
        
        <div class="col-xs-18 col-sm-6 col-md-4">
          <div class="thumbnail">
          <img src="images/api.png" alt="">
              <div class="caption">
                <h4>Adenine phosphoribosyltransferase </h4>
                <p>Adenine phosphoribosyltransferase deficiency has an autosomal recessive pattern of inheritance.</p>  
            </div>
          </div>
        </div> 

        <div class="col-xs-18 col-sm-6 col-md-4">
          <div class="thumbnail">
           <img src="images/nc.png" alt="">
              <div class="caption">
                <h4>Abderhalden–Kaufmann–Lignac syndrome</h4>
                <p>Abderhalden–Kaufmann–Lignac syndrome (AKL syndrome), also called Abderhalden-Lignac-Kaufmann disease or nephropathic cystinosis, is an autosomal recessive renal disorder of childhood comprising cystinosis and renal rickets.</p> 
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-4">
          <div class="thumbnail">
            <img src="images/ks.png" alt="">
              <div class="caption">
                <h4>Lobar nephronia</h4>
                <p>Lobar nephronia refers to an intermediate stage between acute pyelonephritis and renal abscess, and is a focal region of interstitial nephritis. </p> 
            </div>
          </div>
        </div>
        
      </div><!-- End row -->
      
    </div><!-- End container -->
 
	
    <div class="container">
		<div class="row">			
			<!-- Article content -->
			<article class="col-sm-12 maincontent"> 
				<h3>Acute Phosphate Nephropathy</h3>
				<p>Acute phosphate nephropathy (APN) is an underrecognized cause of both acute and chronic renal failure. Individuals with decreased renal function who are exposed to high doses of phosphorous are susceptible to developing APN. The risk for APN is increased in patients with underlying chronic kidney disease, older age, and female sex and in patients taking angiotensin-converting enzyme inhibitors, angiotensin-receptor blockers, diuretics, or nonsteroidal anti-inflammatory drugs (NSAIDs). APN has been reported to occur after exposure to sodium-phosphate (NaP) bowel-cleansing solutions. 
                                Clinically, some patients may present acutely with severe elevations of serum phosphorous and acute kidney injury (AKI); however, the injury may take weeks after exposure to occur, or the finding of an elevated creatinine level may be discovered incidentally weeks or months after the ingestion of these bowel preparations. Therefore, a careful history is important for making this diagnosis. Renal biopsy demonstrates deposition of calcium and phosphorous with damage in the tubulointerstitium. 
                                Patients may have variable outcomes, with some having no recovery of renal function and others recovering some function. There is no particular intervention that can be instituted once the nephropathy occurs. Avoidance of NaP-based bowel-cleansing solutions, particularly by high-risk individuals, is key to preventing APN.</p> </br></br></br>
				
                                <h3>Acute tubular necrosis</h3>	
<p>Acute tubular necrosis (ATN) is a medical condition involving the death of tubular epithelial cells that form the renal tubules of the kidneys. ATN presents with acute kidney injury (AKI) and is one of the most common causes of AKI. Common causes of ATN include low blood pressure and use of nephrotoxic drugs. The presence of "muddy brown casts" of epithelial cells found in the urine during urinalysis is pathognomonic for ATN. Management relies on aggressive treatment of the factors that precipitated ATN (e.g. hydration and cessation of the offending drug). Because the tubular cells continually replace themselves, the overall prognosis for ATN is quite good if the cause is corrected, and recovery is likely within 7 to 21 days.
ATN may be classified as either toxic or ischemic. Toxic ATN occurs when the tubular cells are exposed to a toxic substance (nephrotoxic ATN). Ischemic ATN occurs when the tubular cells do not get enough oxygen, a condition that they are highly sensitive and susceptible to, due to their very high metabolism. Acute tubular necrosis is classified as a "renal" (i.e. not pre-renal or post-renal) cause of acute kidney injury. Diagnosis is made by a FENa (fractional excretion of sodium) > 3% and presence of muddy casts (a type of granular cast) in urinalysis. On histopathology, there is usually tubulorrhexis, that is, localized necrosis of the epithelial lining in renal tubules, with focal rupture or loss of basement membrane.
Proximal tubule cells can shed with variable viability and not be purely "necrotic". Toxic ATN can be caused by free hemoglobin or myoglobin, by medication including antibiotics such as aminoglycoside, statins such as atorvastatin, and cytoxic drugs such as cisplatin, or by intoxication (ethylene glycol, "anti-freeze"). Histopathology: Toxic ATN is characterized by proximal tubular epithelium necrosis (no nuclei, intense eosinophilic homogeneous cytoplasm, but preserved shape) due to a toxic substance (poisons, organic solvents, drugs, heavy metals). Necrotic cells fall into the tubule lumen, obturating it, and determining acute renal failure. Basement membrane is intact,[citation needed] so the tubular epithelium regeneration is possible. Glomeruli are not affected.
Ischemic ATN can be caused when the kidneys are not sufficiently perfused for a long period of time (i.e. renal artery stenosis) or during shock. Hypoperfusion can also be caused by embolism of the renal arteries. Ischemic ATN specifically causes skip lesions through the tubules.</p></br></br></br>				
				

<h3>Adenine phosphoribosyltransferase deficiency</h3>
				<p>Adenine phosphoribosyltransferase deficiency (also called APRT deficiency or 2,8 dihydroxyadenine urolithiasis) is an autosomal recessive metabolic disorder associated with a mutation in the enzyme adenine phosphoribosyltransferase. The disorder results in accumulation of the insoluble purine 2,8-dihydroxyadenine. It can result in nephrolithiasis (kidney stones), acute renal failure and permanent kidney damage.

More than 300 individuals with this disease have been reported world-wide but it is not known how common this medical problem truly is. Patients with the disease deficiency lack the enzyme adenine phosphoribosyltransferase and therefore have difficulties breaking down dietary substances called purines, resulting in accumulation of a compound called 2,8-dihydroxyadenine (2,8-DHA) that is excreted by the kidneys. Interestingly, up to 70% of affected patients, have red hair or relatives with this hair color. APRT deficiency is inherited in an autosomal recessive manner. This means the defective gene responsible for the disorder is located on an autosome, and two copies of the defective gene (one inherited from each parent) are required in order to be born with the disorder. 
The parents of an individual with an autosomal recessive disorder both carry one copy of the defective gene, but usually do not experience any signs or symptoms of the disorder. Most patients with APRT deficiency have repeated episodes of kidney stones that are not detected by a conventional x-ray study. However, all stones are easily detected by other medical imaging methods such as ultrasound or computerized tomography (CT) scan. A minority of patients develop symptoms of kidney failure. Kidney stones are often associated with severe loin or abdominal pain. Symptoms associated with kidney failure are largely nonspecific such as increased fatigue and weakness, poor appetite, and weight loss. Children with the disease may have similar symptoms as adults. In young children, APRT deficiency can cause reddish-brown diaper spots.</p> </br></br></br>
				
                                
                                
                                <h3>Nephritis</h3>
				<p> Nephritis is inflammation of the kidneys and may involve the glomeruli, tubules, or interstitial tissue surrounding the glomeruli and tubules. Medical conditions that are associated with Nephritis are Glomerulonephritis which is the  inflammation of the glomeruli. Glomerulonephritis is often implied when using the term "nephritis" without qualification and Interstitial nephritis or tubulo interstitial nephritis which is the inflammation of the spaces between renal tubules. Nephritis can produce glomerular injury, by disturbing the glomerular structure with inflammatory cell proliferation. This can lead to reduced glomerular blood flow, leading to reduced urine output (oliguria)and retention of waste products (uremia). As a result, red blood cells may leak out of damaged glomeruli, causing blood to appear in the urine (hematuria).
                                Low renal blood flow activates the renin-angiotensin-aldosterone system (RAAS), causing fluid retention and mild hypertension. As the kidneys inflame, they begin to excrete needed protein from the body into the urine stream. This condition is called proteinuria. Loss of necessary protein due to nephritis can result in several life-threatening symptoms. The most serious complication of nephritis can occur if there is significant loss of the proteins that keep blood from clotting excessively. Loss of these proteins can result in blood clots causing sudden stroke. Nephritis represents the ninth most common cause of death among all women in the US (and the fifth leading cause among non-Hispanic black women). Worldwide the highest rates of nephritis are 50-55% for African or Asian descent, then Hispanic at 43% and Caucasian at 17%. </p> 
								
			</article>	
		</div>
        
       </div>
	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					<div class="col-md-5 panel">
						<h3 class="panel-title">Latest News</h3>
						<div class="panel-body">
							<p>The Cape Kidney Association this year was invited to exhibit at the World Congress of Nephrology that was held for the first time in South Africa at the CTICC with approximately 3000 medical specialists attending the congress.
            At the congress our Executive Fund Manager, Molly Fabe was appointed as the ambassador for South Africa. We also had our first international booklet about the company published by our interns Sisonke and Pumela and it was distributed to every delegate during the congress.</p> 
						</div>
					</div>

					<div class="col-md-4 panel contact"> 
						<h3 class="panel-title">Contact Info</h4>
						<div class="panel-body">
						<p>The Cape Kidney Association is managed by Molly Fabe, Executive Manager, and assisted by Vanessa Hallet, Office Administrator.</p>
						<ul>
						  <li><i class="fa fa-phone"></i>021 761 1326</li>
						  <li><a href="mailto:capekidney@xsinet.co.za"><i class="fa fa-envelope-o"></i> capekidney@xsinet.co.za</a></li>
						  <li><i class="fa fa-flag"></i>17 Torrens Road Golf Link Estate Wynberg 7800</li>
						</ul> 
						</div>
					</div>

					<div class="col-md-3 panel">
						<h3 class="panel-title">Follow Us</h3>
						<div class="panel-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								
								
								<a href="https://www.facebook.com/CapeKidneyAssociation?fref=ts"><i class="fa fa-facebook fa-2"></i></a>
								
							</p>	
						</div>
					</div>
			
				</div> <!-- /row of panels -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="simplenav">
								<a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a> | <a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About Us') ?></a> | <a href="<?php echo $this->url('kidney') ?>"><?php echo $this->translate('Kidney disease') ?></a> | <a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a> | <a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a> | <a href="<?php echo $this->url('news') ?>"><?php echo $this->translate('Newsletter') ?> </a> </p>
							</p>
						</div>
					</div>

					<div class="col-md-6 panel">
						<div class="panel-body">
							<p class="text-right">
								<a href="index2.html"><img src="img/images/f.png" alt="" width="100" height="25" /></a>                                                                                                                                                                                                                                                                                                                                                                                                                                  
				<a href="index2.html"><img src="img/images/g.png" alt="" width="100" height="25" /></a>                         
				<a href="index2.html"><img src="img/images/l.jpg" alt="" width="130" height="25" /></a>                        
				<a href="index2.html"><img src="img/images/m.png" alt="" width="100" height="25" /></a>               
 
							</p>
						</div>

				</div> <!-- /row of panels -->
			</div>
		</div>

	</footer>	
		




	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="js/headroom.min.js"></script>
	<script src="js/jQuery.headroom.min.js"></script>
	<script src="js/custom.js"></script>
</body>
</html>
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

